services:
  api:
    build:
      context: .
      target: build
    image: backend-dev/api:1.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev

volumes:
  node_modules: