Product:
  type: object
  required:
    - id
    - name
    - category
    - price
  properties:
    id:
      type: string
      description: The unique identifier for the product.
    name:
      type: string
      description: The name of the product.
    categoryId:
      type: string
      description: The ID of the associated category.
    price:
      type: number
      description: The price of the product.
    attributes:
      type: object
      additionalProperties: true
