openapi: 5.0.1
info:
  title: Category API
  description: A CRUD API for managing categories.
  version: 1.0.0

/category:
  get:
    tags:
      - Category
    summary: Get all categories.
    description: Retrieves a list of all categories.
    responses:
      "200":
        description: A list of all categories.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#components/schemas/Category"

  post:
    tags:
      - Category
    summary: Create a new category.
    description: Add a new category.
    requestBody:
      required: true
      content:
        application/json:
          $ref: "#components/schemas/Category"
    responses:
      "201":
        description: Category created successfully.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"

/category/${id}:
  get:
    tags:
      - Category
    summary: Get a category by ID.
    description: Retrieves a category based on the category ID.
    parameters:
      - name: id
        in: path
        description: The unique ID of the category.
        required: true
        schema:
          type: string
    responses:
      "200":
        description: A category object.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      "404":
        description: Category not found.

  put:
    tags:
      - Category
    summary: Update a category by ID.
    description: Update an existing category details based on category ID.
    parameters:
      - name: id
        in: path
        description: The unique ID of the category.
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Category"
    responses:
      "200":
        description: A category object.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      "404":
        description: Category not found.

  delete:
    tags:
      - Category
    summary: Delete a category by ID.
    description: Delete a category based on category ID.
    parameters:
      - name: id
        in: path
        description: The unique ID of the category.
        required: true
        schema:
          type: string
    response:
      "204":
        description: Category deleted successfully.
      "404":
        description: Category not found.
