name: Node.js CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Docker build stage
        run: docker build --target build -t backend-build .
        working-directory: ./backend

      - name: Run tests in container
        run: docker run --rm backend-build npm test
        working-directory: ./backend

      - name: Run Docker prod stage
        run: docker build --target prod -t backend-prod .
        working-directory: ./backend
